window.CURRICULUM_TAGS = {
  "Telugu": [
    "వ్యాకరణం",
    "పద్యాలు",
    "సంధులు",
    "సమాసాలు",
    "జాతీయాలు",
    "లేఖ రచన",
    "వ్యాస రచన",
    "కథలు",
    "భాషా భాగాలు",
    "అలంకారాలు",
    "ఛందస్సు",
    "పాఠ్యభాగం"
  ],
  "Mathematics": [
    "Ch1_Real_Numbers",
    "Ch1_Real_Numbers_Introduction",
    "Ch1_Euclids_Division_Lemma",
    "Ch1_The_Fundamental_Theorem_of_Arithmetic",
    "Ch1_Revisiting_Irrational_Numbers",
    "Ch1_Revisiting_Rational_Numbers",
    "Ch1_Real_Numbers_Summary",
    "Ch2_Polynomials",
    "Ch2_Polynomials_Introduction",
    "Ch2_Geometrical_Meaning_of_Zeroes",
    "Ch2_Relationship_Zeroes_Coefficients",
    "Ch2_Division_Algorithm",
    "Ch2_Polynomials_Summary",
    "Ch3_Pair_of_Linear_Equations_in_Two_Variables",
    "Ch3_Linear_Equations_Introduction",
    "Ch3_Graphical_Method_of_Solution",
    "Ch3_Algebraic_Methods",
    "Ch3_Substitution_Method",
    "Ch3_Elimination_Method",
    "Ch3_Cross_Multiplication_Method",
    "Ch3_Equations_Reducible",
    "Ch3_Linear_Equations_Summary",
    "Ch4_Quadratic_Equations",
    "Ch4_Quadratic_Equations_Introduction",
    "Ch4_Solution_by_Factorisation",
    "Ch4_Solution_by_Completing_Square",
    "Ch4_Nature_of_Roots",
    "Ch4_Quadratic_Equations_Summary",
    "Ch5_Arithmetic_Progressions",
    "Ch5_AP_Introduction",
    "Ch5_nth_Term_of_AP",
    "Ch5_Sum_First_n_Terms",
    "Ch5_AP_Summary",
    "Ch6_Triangles",
    "Ch6_Triangles_Introduction",
    "Ch6_Similar_Figures",
    "Ch6_Similarity_of_Triangles",
    "Ch6_Criteria_for_Similarity",
    "Ch6_Areas_of_Similar_Triangles",
    "Ch6_Pythagoras_Theorem",
    "Ch6_Triangles_Summary",
    "Ch7_Coordinate_Geometry",
    "Ch7_Coordinate_Geometry_Introduction",
    "Ch7_Distance_Formula",
    "Ch7_Section_Formula",
    "Ch7_Area_of_Triangle",
    "Ch7_Coordinate_Geometry_Summary",
    "Ch8_Introduction_to_Trigonometry",
    "Ch8_Trigonometry_Introduction",
    "Ch8_Trigonometric_Ratios",
    "Ch8_Ratios_Specific_Angles",
    "Ch8_Ratios_Complementary_Angles",
    "Ch8_Trigonometric_Identities",
    "Ch8_Trigonometry_Summary",
    "Ch9_Some_Applications_of_Trigonometry",
    "Ch9_Applications_Introduction",
    "Ch9_Heights_and_Distances",
    "Ch9_Trigonometry_Applications_Summary",
    "Ch10_Circles",
    "Ch10_Circles_Introduction",
    "Ch10_Tangent_to_Circle",
    "Ch10_Number_of_Tangents",
    "Ch10_Circles_Summary",
    "Ch11_Constructions",
    "Ch11_Constructions_Introduction",
    "Ch11_Division_of_Line_Segment",
    "Ch11_Construction_of_Tangents",
    "Ch11_Constructions_Summary",
    "Ch12_Areas_Related_to_Circles",
    "Ch12_Areas_Related_Circles_Introduction",
    "Ch12_Perimeter_and_Area_Review",
    "Ch12_Areas_Sector_and_Segment",
    "Ch12_Areas_Combinations_Plane_Figures",
    "Ch12_Areas_Related_Circles_Summary",
    "Ch13_Surface_Areas_and_Volumes",
    "Ch13_Surface_Areas_Volumes_Introduction",
    "Ch13_Surface_Area_Combination_Solids",
    "Ch13_Volume_Combination_Solids",
    "Ch13_Conversion_of_Solid",
    "Ch13_Frustum_of_Cone",
    "Ch13_Surface_Areas_Volumes_Summary",
    "Ch14_Statistics",
    "Ch14_Statistics_Introduction",
    "Ch14_Mean_of_Grouped_Data",
    "Ch14_Mode_of_Grouped_Data",
    "Ch14_Median_of_Grouped_Data",
    "Ch14_Graphical_Representation",
    "Ch14_Statistics_Summary",
    "Ch15_Probability",
    "Ch15_Probability_Introduction",
    "Ch15_Theoretical_Approach",
    "Ch15_Probability_Summary"
  ],
  "Science": [
    "Physics",
    "Chemistry",
    "Biology",
    "Photosynthesis",
    "Gravity",
    "Periodic Table",
    "Ecosystem",
    "Genetics",
    "Forces & Motion",
    "Cell Structure",
    "Chemical Reactions",
    "Light & Reflection",
    "Electricity"
  ],
  "English": [
    "Grammar",
    "Tenses",
    "Vocabulary",
    "Reading Comprehension",
    "Writing Skills",
    "Poetry",
    "Prose",
    "Prepositions",
    "Adjectives",
    "Nouns & Verbs",
    "Direct & Indirect Speech",
    "Active & Passive Voice"
  ],
  "Social Studies": [
    "History",
    "Geography",
    "Civics",
    "Economics",
    "French Revolution",
    "Indian Constitution",
    "Map Work",
    "Climate Change",
    "World War I",
    "World War II",
    "Democracy"
  ]
};
